version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      # Install dependencies needed for running tests
      - npm install
      - npm install --save-dev @babel/core @babel/node

      # Upgrade AWS CLI to the latest version
      - pip3 install --upgrade awscli
  pre_build:
    commands:
      - npm install --save-dev @babel/node
